### ISSUE TITLE
No known instance method for selector 'setPushTokenHex:'

### ISSUE THREAD

**Issue by ACOSW** [JivoChat/JivoSDK-iOS#1]
При подключении JivoSDK-iOS в существующий проект на ReactNative xcode выдает ошибку в файле JivoSDKModule.m

No known instance method for selector 'setPushTokenHex:'

<img width="944" alt="Снимок экрана 2022-05-04 в 10 29 14" src="https://user-images.githubusercontent.com/6252660/166632410-00d88815-64e9-40e1-95c2-106a07575e93.png">

Xcode 13.3.1
Cocoapods 1.11.3
React-Native 0.66.4

**Comment by bronenos** [comment]
Эта проблема должна решиться вместе с обновлением до последней версии (на данный момент 2.1.3)
