### ISSUE TITLE
Crash on startup with Lottie reference

### ISSUE THREAD

**Issue by scoremedianl** [JivoChat/JivoSDK-iOS#12]
dyld[21864]: Symbol not found: _$s13JMTimelineKit0A8ResourceO6lottieyAC6Lottie9AnimationCcACmFWC
  Referenced from: <566BE347-4588-35D6-8B29-73D72E0E7970> /private/var/containers/Bundle/Application/117E7B35-ADD2-4344-8B2E-AA485B6F49F3/XpertData.app/Frameworks/JivoSDK.framework/JivoSDK
  Expected in:     <3C96CB8C-3EFB-301A-8012-BCCEBB922A24> /private/var/containers/Bundle/Application/117E7B35-ADD2-4344-8B2E-AA485B6F49F3/XpertData.app/Frameworks/JMTimelineKit.framework/JMTimelineKit

Xcode: 15
iOS 17.0.3

Installed trough Cocoapods. No errors when compiling, lottie not included in podfile only JivoSDK.

**Comment by bronenos** [comment]
Which SDK version you have?

**Comment by scoremedianl** [comment]
We use the latest version trough CocoaPods.

Vriendelijke groeten,

Ruben Groothuis 
Director 

  <yourlinkedinurl>	
	+31 657050014
	***@***.***  ***@***.***>
	www.scoreagency.nl  <http://www.scoreagency.nl/>
	De Heurne 40, 7511GW Enschede

**Comment by bronenos** [comment]
Did you have any problems previously, or this is you first time with Jivo?

**Comment by scoremedianl** [comment]
First time using the JivoChat SDK.

Ruben Lucas Groothuis
Director
 
Score Agency

t:	+31 53 8700020  m: +31 657050014
a:	De Heurne 40, 7511GW Enschede
w:	scoreagency.nl <https://scoreagency.nl/>  e: ***@***.*** ***@***.***>

 <https://www.facebook.com/ScoreAgencyNL>   <https://twitter.com/scoremedianl>   <https://www.instagram.com/scoreagency.nl/>
 
De informatie in dit e-mailbericht is uitsluitend bestemd voor de geadresseerde en heeft daarmee de status vertrouwelijk. Openbaarmaking, vermenigvuldiging, verspreiding en/of verstrekking van deze informatie aan derden is niet toegestaan zonder voorafgaande schriftelijke toestemming van Score Media B.V. Nederland of aandeelhouders wijst iedere aansprakelijkheid af voor schade ten gevolge van een onjuiste, onvolledige en ontijdige verzending en ontvangst van de inhoud van deze e-mail. Wij zijn niet aansprakelijk voor eventuele virussen. U wordt verzocht bij onjuiste adressering de afzender direct te informeren en het bericht te vernietigen. Wij adviseren u om bij twijfel over de juistheid of de volledigheid van het e-mailbericht contact met de afzender op te nemen. Indien Bij gebruik van de inhoud van deze e-mail aanvaardt u de disclaimer.

**Comment by bronenos** [comment]
We have just released the 4.0.4 version, please check it
