### ISSUE TITLE
Не приходят пуш уведомления

### ISSUE THREAD

**Issue by Semen110996** [JivoChat/JivoSDK-iOS#15]
В канале для SDK файл p8, Key ID, Team ID, Bundle ID указаны, метод setPushToken из SDK в приложении вызывается, сборка выложена в тестфлай и установлена из него, но пуши не приходят. Пуши которые отправляет наш сервер в приложение приходят, от JivoChat нет. Как можно посмотреть логи и понять причину проблемы?

**Comment by Semen110996** [comment]
In the channel for the SDK, the file p8, Key ID, Team ID, Bundle ID are indicated, the setPushToken method from the SDK is called in the application, the assembly is uploaded to testfly and installed from it, but push notifications do not arrive. The push notifications that our server sends to the application do not come from JivoChat. How can I look at the logs and understand the cause of the problem?

**Comment by akaraul** [comment]
@Semen110996 добрый день! как в итоге решили проблему?
