### ISSUE TITLE
Flutter - ios - push Notification UI

### ISSUE THREAD

**Issue by 1AlexFix1** [JivoChat/JivoSDK-iOS#16]
Hello on ios, when the application is open, a push comes and instead of the application name, the project name is substituted in the case of flutter Runner, and we cannot change this name
![photo_2024-06-24_20-40-29](https://github.com/JivoChat/JivoSDK-iOS/assets/44409006/64c41c45-bcaa-465c-a3ae-764f9c6a77c4)

**Comment by bronenos** [comment]
On our side, we send notification payloads without your app name

So we suggest you to look deeper into your configurations, Info plist keys, to assign another "display name" for your app

**Comment by 1AlexFix1** [comment]
merci
