### ISSUE TITLE
Markdown разметка

### ISSUE THREAD

**Issue by jemzza** [JivoChat/JivoSDK-iOS#4]
В чате не работает mardown разметка. Подскажите она вообще реализована в сдк? Если нет, то когда вы ее добавите?

В android sdk она есть

**Comment by dzolotarev** [comment]
Здравствуйте! Свяжитесь, пожалуйста, с нашей техподдержкой в чате на сайте jivo.ru. Спасибо.

**Comment by bronenos** [comment]
Поддержка markdown ожидается уже в ближайшей версии

**Comment by bronenos** [comment]
Поддержка markdown ожидается уже в ближайшей версии 3.1.1

**Comment by bronenos** [comment]
Версия 3.1.1 стала доступна
