### ISSUE TITLE
/Users/userName/Library/Developer/Xcode/DerivedData/testJivoProj-fgjivwhwoywbwhciislfowlpflul/Build/Products/Debug-iphoneos/testJivo.app/Assets.car

### ISSUE THREAD

**Issue by OybekMaximum** [JivoChat/JivoSDK-iOS#7]
After installing JivoChat, app doesn't run and there was an error that is /Users/userName/Library/Developer/Xcode/DerivedData/testJivoProj-fgjivwhwoywbwhciislfowlpflul/Build/Products/Debug-iphoneos/testJivo.app/Assets.car
and I checked build phases for any duplicates but can't find

**Comment by bronenos** [comment]
What exactly does it say?
