### ISSUE TITLE
Keyboard issue

### ISSUE THREAD

**Issue by trying2** [JivoChat/JivoSDK-iOS#8]
Описание проблемы: После закрытия любого вьюконтроллера, который открыт поверх чата с открытой клавиатурой проставляются неправильные инсеты
Шаги воспроизведения проблемы: На экране с чатом начать вводить текст, открыть модалку для выбора фото, закрыть ее. После закрытия клавиатура наезжает на текстфилд
Ожидаемый результат: Клавитура не наезжает на текстфилд
Фактический результат: Клавитура наезжает на текстфилд
Регулярность или условия возникновения проблемы: Всегда
Фрагмент кода, демонстрирующий проблему (в идеале – полноценный проект Xcode, который мы можем запустить на своей стороне):

<img width="486" alt="Снимок экрана 2023-06-15 в 20 14 57" src="https://github.com/JivoChat/JivoSDK-iOS/assets/10727274/cf729eaa-88fa-4f72-b673-fac08b24361e">
<img width="542" alt="Снимок экрана 2023-06-15 в 20 14 45" src="https://github.com/JivoChat/JivoSDK-iOS/assets/10727274/6d4e5563-7243-49a5-95b2-1628816ab13f">
<img width="315" alt="Снимок экрана 2023-06-15 в 20 16 35" src="https://github.com/JivoChat/JivoSDK-iOS/assets/10727274/b46cf058-05d3-4441-860a-b73db4f1322c">

Конфигурация версий нашего SDK и его зависимостей из ваших файлов Podfile и Podfile.lock (в идеале - эти файлы полностью) - JivoSDK (3.3.1):
Информация о вашем окружении: версии macOS, Xcode, CocoaPods

```
- System
ProductName:		macOS
ProductVersion:		13.4
BuildVersion:		22F66

- Xcode
/Users/erniki/Downloads/Xcode.app/Contents/Developer
Xcode 14.3.1
Build version 14E300c

- CocoaPods
/Users/erniki/.rvm/gems/ruby-2.7.0/bin/pod
1.12.1

- Git
/usr/bin/git
git version 2.39.2 (Apple Git-143)

- Bash
/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22)
```

**Comment by bronenos** [comment]
На актуальных версиях проблема, по всей видимости, не сохраняется
